name: atlas_icons
description: Open source icons library, Icons available in SVG format, Font, Figma, Adobe XD and Iconjar Libraries.
version: 0.0.7
homepage: http://vectopus.com/atlas-icons

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
    # - assets/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Atlas-Icons
      fonts:
        - asset: lib/fonts/audio/audio.ttf
        - asset: lib/fonts/basic-ui/basic-ui.ttf
        - asset: lib/fonts/business-finance/business-finance.ttf
        - asset: lib/fonts/christmas/christmas.ttf
        - asset: lib/fonts/cinema/cinema.ttf
        - asset: lib/fonts/communication/communication.ttf
        - asset: lib/fonts/construction/construction.ttf
        - asset: lib/fonts/content-box/content-box.ttf
        - asset: lib/fonts/data-document/data-document.ttf
        - asset: lib/fonts/ecology/ecology.ttf
        - asset: lib/fonts/electronic-gadget/electronic-gadget.ttf
        - asset: lib/fonts/fitness-gym/fitness-gym.ttf
        - asset: lib/fonts/food-beverage/food-beverage.ttf
        - asset: lib/fonts/furniture/furniture.ttf
        - asset: lib/fonts/hand-gesture/hand-gesture.ttf
        - asset: lib/fonts/hotel-service/hotel-service.ttf
        - asset: lib/fonts/internet-security/internet-security.ttf
        - asset: lib/fonts/laboratory/laboratory.ttf
        - asset: lib/fonts/marketing/marketing.ttf
        - asset: lib/fonts/medical/medical.ttf
        - asset: lib/fonts/real-estate/real-estate.ttf
        - asset: lib/fonts/school/school.ttf
        - asset: lib/fonts/social/social.ttf
        - asset: lib/fonts/thanksgiving/thanksgiving.ttf
        - asset: lib/fonts/transportation/transportation.ttf
        - asset: lib/fonts/travel/travel.ttf
        - asset: lib/fonts/virtual-reality/virtual-reality.ttf
        - asset: lib/fonts/weather/weather.ttf
        - asset: lib/fonts/web-design/web-design.ttf
        - asset: lib/fonts/winter/winter.ttf
        - asset: lib/fonts/world-monuments/world-monuments.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
