name: atlas_icons
description: Open source icons library, Icons available in SVG format, Font, Figma, Adobe XD and Iconjar Libraries.
version: 0.0.10
homepage: http://vectopus.com/atlas-icons

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
    # - assets/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Atlas-audio
      fonts:
        - asset: lib/fonts/audio/audio.ttf

    - family: Atlas-basic-ui
      fonts:
        - asset: lib/fonts/basic-ui/basic-ui.ttf

    - family: Atlas-business-finance
      fonts:
        - asset: lib/fonts/business-finance/business-finance.ttf

    - family: Atlas-christmas
      fonts:
        - asset: lib/fonts/christmas/christmas.ttf

    - family: Atlas-cinema
      fonts:
        - asset: lib/fonts/cinema/cinema.ttf
    
    - family: Atlas-communication
      fonts:
        - asset: lib/fonts/communication/communication.ttf

    - family: Atlas-construction
      fonts:
        - asset: lib/fonts/construction/construction.ttf

    - family: Atlas-content-box
      fonts:
        - asset: lib/fonts/content-box/content-box.ttf

    - family: Atlas-data-document
      fonts:
        - asset: lib/fonts/data-document/data-document.ttf
    
    - family: Atlas-ecology
      fonts:
        - asset: lib/fonts/ecology/ecology.ttf

    - family: Atlas-electronic-gadge
      fonts:    
        - asset: lib/fonts/electronic-gadget/electronic-gadget.ttf

    - family: Atlas-fitness-gym
      fonts:
        - asset: lib/fonts/fitness-gym/fitness-gym.ttf

    - family: Atlas-food-beverage
      fonts:    
        - asset: lib/fonts/food-beverage/food-beverage.ttf

    - family: Atlas-furniture
      fonts: 
        - asset: lib/fonts/furniture/furniture.ttf

    - family: Atlas-hand-gesture
      fonts:
        - asset: lib/fonts/hand-gesture/hand-gesture.ttf

    - family: Atlas-hotel-service
      fonts:
        - asset: lib/fonts/hotel-service/hotel-service.ttf

    - family: Atlas-internet-security
      fonts:    
        - asset: lib/fonts/internet-security/internet-security.ttf

    - family: Atlas-laboratory
      fonts: 
        - asset: lib/fonts/laboratory/laboratory.ttf

    - family: Atlas-love
      fonts: 
        - asset: lib/fonts/love/love.ttf

    - family: Atlas-marketing
      fonts:     
        - asset: lib/fonts/marketing/marketing.ttf

    - family: Atlas-medical
      fonts:    
        - asset: lib/fonts/medical/medical.ttf

    - family: Atlas-real-estate
      fonts: 
        - asset: lib/fonts/real-estate/real-estate.ttf

    - family: Atlas-school
      fonts: 
        - asset: lib/fonts/school/school.ttf

    - family: Atlas-social
      fonts:     
        - asset: lib/fonts/social/social.ttf

    - family: Atlas-thanksgiving
      fonts: 
        - asset: lib/fonts/thanksgiving/thanksgiving.ttf

    - family: Atlas-transportation
      fonts:
        - asset: lib/fonts/transportation/transportation.ttf

    - family: Atlas-travel
      fonts:
        - asset: lib/fonts/travel/travel.ttf

    - family: Atlas-virtual-reality
      fonts:
        - asset: lib/fonts/virtual-reality/virtual-reality.ttf

    - family: Atlas-weather
      fonts:
        - asset: lib/fonts/weather/weather.ttf

    - family: Atlas-web-design
      fonts:
        - asset: lib/fonts/web-design/web-design.ttf

    - family: Atlas-winter
      fonts:
        - asset: lib/fonts/winter/winter.ttf

    - family: Atlas-world-monument
      fonts:
        - asset: lib/fonts/world-monuments/world-monuments.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
